language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
  licenses:
    - 'android-sdk-license-.+'

notifications:
  email: true

sudo: false

script:
- ./gradlew test